
-- DELETE FROM SPRING_SESSION_ATTRIBUTES;


-- CREATE TABLE SPRING_SESSION_ATTRIBUTES (
--     SESSION_PRIMARY_ID CHAR(36) NOT NULL,
--     ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
--     ATTRIBUTE_BYTES BLOB NOT NULL,
--     CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
--     CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
-- ) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

-- CREATE TABLE testing (
--     id int PRIMARY KEY,
--     uid varchar(88),
--     data int,
--     FOREIGN KEY (uid) REFERENCES UserDetails(UserName)
--     )

insert into testing(id,uid,data)
    values(3,'ram',12),
    (4,'ram',13)

-- CREATE TABLE UserDetails (
--     FirstName VARCHAR(99),
--     LastName VARCHAR(99),
--     UserName VARCHAR(99) PRIMARY KEY,
--     Password int
-- )
-- DROP TABLE UserDetails


-- CREATE TABLE testing (
--     id INT PRIMARY KEY,
--     uid VARCHAR(99),
--     data int,
--     FOREIGN KEY(uid) REFERENCES UserDetails(UserName)
-- )




-- DELETE FROM SPRING_SESSION_ATTRIBUTES